Resources/config/services.xml

In Symfony's convention, the listeners priorities are from -255 to 255, therefore a priority of 10000 is... a bit high. The main problem of not being in the conventions is that it also disallow other listeners to be the first ones, without knowing about this bundle.
I changed it to 250 so this is an extremely high value that still allows other listeners to be placed before this one (not technically but in the priority conventions).

Decrease the listener priority

---

EventListener/CorsListener.php

My scenario is that the preflight OPTIONS request is occurring on a HTTP DELETE request.
In this scenario, only the `Access-Control-Request-Method: DELETE` header is specified, and not `Access-Control-Allow-Headers`. As a result, line 117 would set this header to null value.
This PR proposes to safeguard this logic to only set this header when required.

Access-Control-Allow-Headers should not be set if the value is null.

---

DependencyInjection/Configuration.php
EventListener/CorsListener.php
README.md
Tests/CorsListenerTest.php

See https://github.com/nelmio/NelmioCorsBundle/issues/66
Feature + preflight requests tested
"Normal" response tested + refactoring of `CorsListener::options` attribute
=> because `$this->options` was always empty while executing `CorsListener::onKernelResponse()`... I don't think it's the case in production environment (I hope so), but at least in test environment: I just couldn't find a way to make it work the way it was done before :(

Add an option to force Access-Control-Allow-Origin value

---

EventListener/CorsListener.php
Tests/CorsListenerTest.php

Fix #66 (cache issues)
Because the `forced_allow_origin_value` option is only useful for the cache issues... but it doesn't solve it yet.
Note: As @Seldaek said, we could also set a `Vary: Origin` header to workaround the cache issues instead of merging this PR (if the cache system supports it).

rework forced_allow_origin_value option to always set the header

---

DependencyInjection/NelmioCorsExtension.php

If there are no paths, the `NelmioCorsExtension::load()` method will return early:
```php
if (!$config['paths']) {
return;
}
```
This effectively prevents loading the default configuration, therefore we now have to configure a workaround in our `config.yml`:
```yml
nelmio_cors:
paths: { '^/': [] } # the NelmioCorsExtension does not load if there are no paths
```
In Contao, we dynamically provide the CORS settings, so we actually do not need to configure any paths. But we do need the `NelmioCorsExtension` class to load. 😄 
This pull request encapsulates the paths related routines in an if condition. Of course, I can also move it to a separate method if you prefer. Just let me know.

Always load the default settings

---

EventListener/CorsListener.php
Tests/CorsListenerTest.php

Hey Jordi 😄 
Just had an issue where my browser cache went crazy because the response of my API was still in the cache even though I developed locally. This is due to the missing `Vary` header on the `Origin` header.
More on that: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#CORS_and_caching

Make sure the preflight responses vary per Origin

---

EventListener/CorsListener.php

This MR adds a check for preflight headers when deciding whether to treat the request as a "normal" request or a preflight request according to the CORS specification.
As mentioned in issue #100 , preflight CORS `OPTIONS` requests are characterized by having an `Access-Control-Request-Method` header, which regular CORS `OPTIONS` request doesn't. Without this fix, valid CORS `OPTIONS` requests are denied because they are immediately treated as preflight requests due to simply being `OPTIONS` requests with a different `Origin` header value than the current host. This is not according to the `CORS` specification, and causes this bundle to hijack valid `OPTIONS` requests which happen to be CORS, but not preflight requests.
The solution was given in issue #100 by @LPodolski, this is just a PR …

Allow non-preflight OPTION requests (fixes #100)

---

.travis.yml
EventListener/CorsListener.php
Tests/CorsListenerTest.php
Tests/DependencyInjection/CorsConfigurationProviderPassTest.php
Tests/Fixtures/ProviderMock.php
Tests/Options/ResolverTest.php
composer.json
phpunit.xml.dist

This is probably going to need a few changes based on feedback. I just thought I'd get it all together & testable first.
~There are two related upstream PRs for SymfonyTest https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/pull/121 and https://github.com/SymfonyTest/SymfonyConfigTest/pull/63 to make the DI test package work.~
~That is where part of the version bump(s) come in. The package has a BC break in signatures after v3, and v4 requires PHPUnit 8 for `TestCase` compatibility.~
So please let me know what more is wanted, or not, and I'll happily work to get this over the line :smiley_cat: 
Summary
-------
- Drop PHP < 7.1 ~7.2~
- Drop Symfony < 4.3 ~4.0~
- Deprecations for HttpKernel Events
- Drop matthiasnoback/symfony-dependency-injection-test
- ~Update Travis to use …

Support for Symfony 5

---

Resources/config/services.xml

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | **yes**
| Deprecations? | no
| Fixed tickets | #115

Downgrade CorsListener priority

---

EventListener/CorsListener.php
Resources/config/services.xml
Tests/CorsListenerTest.php

Hi, 
I am playing with servers that allows a kernel to handle multiple requests ([php-pm](https://github.com/php-pm/php-pm), [roadrunner](https://github.com/spiral/roadrunner)).
The current version of the CorsListener leads to memory leaks in this context (adding the same listeners on each request).
In this PR:
- `onKernelRequest` stores flags in the request attributes instead of adding listener on the dispatcher
- `onKernelResponse` is always registered and checks these flags to choose what needs to be done

Do not mutate EventDispatcher at runtime

---

EventListener/CorsListener.php
Tests/CorsListenerTest.php

Hey. Just a security improvement. It seems like if a request `Origin` is not allowed, `Access-Control-Allow-Origin` shouldn't be returned in a response. 
https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null

Remove null 'Access-Control-Allow-Origin' if origin check has failed

---

EventListener/CorsListener.php

Firstly, I understand the CORS concept and I'm not using the origin wildcard in production, but this PR should fix some unexpected behavior.
In my experience, and perhaps I may have been approaching a problem incorrectly, Symfony's environment vars are not yet resolved when the `NelmioCorsExtension` is reached.
If I have:
```yaml
allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
```
in my config, Symfony populates this with a temp env var, not the real value but a placeholder, initially. Looks like the extension beats Symfony to parsing that value, i.e. the env var is not yet populated with its true value.
Consequently, the `NelmioCorsExtension` doesn't read the `*` that I have set in my `.env`, and skips over the following due to a negative string match, i.e. …

added check for runtime env vars in config

---

EventListener/CacheableResponseVaryListener.php
Resources/config/services.xml
Tests/EventListener/CacheableResponseVaryListenerTest.php

fixes #123 
For cacheable responses the `Vary` header should include `Origin` to let caching proxies respect the request's origin.

[RFC] Include `Origin` as `Vary`  header for cacheable responses

---

EventListener/CorsListener.php

This pull request adds sanitation to the response body when unauthorized headers are added to the request payload. The reason for doing so is to prevent cross-side scripting vulnerabilities.
Resolves #162

Sanitize response message for unathorized headers

---

DependencyInjection/Configuration.php
EventListener/CorsListener.php
README.md

I would like to propose introducing a flag that allows the bundle user to opt-out of the default "skip if same as origin" logic done in `CorsListener` (see https://github.com/nelmio/NelmioCorsBundle/blob/master/EventListener/CorsListener.php#L67).
As far as I understand allowing this would not violate the CORS spec.
For us this is a valid usage scenario, for reasons which are a bit convoluted to explain, but in short we have a reverse proxy setup where the symfony backend is not aware of all the domains it can be routed through. In this scenario, we are in fact using an `Origin` header which matches (even though the external facing domain does not) the same scheme & http host the symfony backend "sees".
With this proposed change nothing would change for current users, while allowing the …

Add configuration flag to allow to opt-out from skipping CORS when same as origin

---

Tests/Fixtures/ProviderMock.php

**Fixes:**
```
bin/console hautelook:fixtures:load
Careful, database will be purged. Do you want to continue y/N ?y
Fatal error: Declaration of Fixtures\ProviderMock::getOptions(Symfony\Component\HttpFoundation\Request $request): void must be compatible with Nelmio\CorsBundle\Options\ProviderInterface::getOptions(Symfony\Component\HttpFoundation\Request $request): array in /var/www/html/vendor/nelmio/cors-bundle/tests/fixtures/ProviderMock.php on line 14
09:12:27 CRITICAL  [php] Fatal Compile Error: Declaration of Fixtures\ProviderMock::getOptions(Symfony\Component\HttpFoundation\Request $request): void must be compatible with Nelmio\CorsBundle\Options\ProviderInterface::getOptions(Symfony\Component\HttpFoundation\Request $request): array ["exception" => …
```

Fix Fixtures\ProviderMock interface violation

---

EventListener/CorsListener.php
composer.json

Finding out what is going wrong in prod environments can be tricky sometimes.
This PR allows an optional logger to be passed which enables a debug log.
Now finding out what's happening is a breeze.

Optional debug logging

---

README.md
Resources/doc/index.rst

Similar to https://github.com/nelmio/NelmioSecurityBundle/pull/319
We'd like to publish this bundle on https://symfony.com/bundles To do so, we'd need to update the docs to use RST format.
In addition to changing the doc format, I did the following change in the contents:
```diff
-$ composer req cors
+$ composer require nelmio/cors-bundle
```
In Symfony Docs we do the same. We started using Flex shortcuts, but we found that it's confusing for many readers, so we now use the full and canonical Composer way of installing packages.
Thanks.

Move the docs to RST format to publish it on symfony.com

---

Resources/doc/index.rst

The docs of this bundle are now online: https://symfony.com/bundles/NelmioCorsBundle/current/index.html
I spotted a minor syntax issue and this PR fixes it. Thanks!
A note for people not used to RST syntax. Code blocks are usually defined like this:
```rst
.. code-block:: php
// ...
```
However, since PHP examples are so common in Symfony Docs, we use a trick which consists of this:
```rst
Any normal text here, like a paragraph::
// ... PHP code here
More normal text here [...]
```
The two `::` at the end of any text means that the following indented content is a PHP code block.

[Doc] Fixed a minor syntax issue

---

DependencyInjection/NelmioCorsExtension.php

`The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "Nelmio\CorsBundle\DependencyInjection\NelmioCorsExtension".`

feat: fix deprecation for Extension

---

DependencyInjection/Configuration.php

If we set a default value for the boolean nodes `paths` config, it always overrides the default value in the `defaults` section.
Imagine that we have the following config:
```yaml
nelmio_cors:
defaults:
skip_same_as_origin: false
paths:
'^/':
origin_regex: true
allow_origin: ['^http://localhost:[0-9]+']
```
As a result, we will have `skip_same_as_origin = true` for the `^/` path. This is not expected behaviour.

Remove default values for boolean nodes in paths config
